version: "3.8"
services:
  third-party-web:
    image: node:14-alpine
    volumes:
      - .:/app
    command: sh -c "node --version && npm --version && cd /app && npm i && npm start"
    ports:
      - "3002:3000"
